Update slf4j version
Mini accumulo was failing to start, was seeing the following errors.

```
Thread 'org.apache.accumulo.manager.Manager' died.
java.lang.NoClassDefFoundError: org/slf4j/helpers/AbstractLogger
```

It seems AbstractLogger is an slf4j 2 class that accumulo started using
since 2.1.3.  So this update is probably needed for the integration
branch.