remove reload4j from classpath as it was causing test failures
Was seeing test failure like the following.  Seemed related to having
reload4j on the classpath. Removed it from classpath, do not think it is
needed becasue there is already something providing runtime support for
log4j1.

```
[INFO] ---------------< gov.nsa.datawave:datawave-ingest-core >----------------
[INFO] Building datawave-ingest-core 7.7.0-SNAPSHOT                    [19/116]
[INFO] --------------------------------[ jar ]---------------------------------

[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.099 s -- in datawave.ingest.data.normalizer.SimpleGroupFieldNameParserTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.278 s <<< FAILURE! -- in datawave.util.flag.InputFileTest
[ERROR] datawave.util.flag.InputFileTest.testUpdateDir -- Time elapsed: 0.258 s <<< ERROR!
java.lang.NoSuchMethodError: 'org.apache.logging.log4j.Level org.apache.log4j.helpers.OptionConverter.convertLevel(java.lang.String, org.apache.logging.log4j.Level)'
	at org.apache.log4j.config.PropertiesConfiguration.parseLogger(PropertiesConfiguration.java:416)
	at org.apache.log4j.config.PropertiesConfiguration.configureRoot(PropertiesConfiguration.java:349)
	at org.apache.log4j.config.PropertiesConfiguration.doConfigure(PropertiesConfiguration.java:326)
	at org.apache.log4j.config.PropertiesConfiguration.doConfigure(PropertiesConfiguration.java:127)
	at org.apache.log4j.config.Log4j1Configuration.initialize(Log4j1Configuration.java:59)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:295)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
```